"""create devices table

Revision ID: 99ccd5edb10d
Revises: 
Create Date: 2025-11-10 09:39:16.397287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99ccd5edb10d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('DeviceName', sa.String(length=100), nullable=False),
    sa.Column('DeviceIP', sa.String(length=50), nullable=False),
    sa.Column('DeviceDescription', sa.String(length=255), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=True),
    sa.Column('ImagenDispositivo', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_DeviceName'), 'devices', ['DeviceName'], unique=True)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_DeviceName'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
