"""creando las tablas a usar

Revision ID: c53e67ee792d
Revises: 99ccd5edb10d
Create Date: 2025-11-10 10:05:01.008154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c53e67ee792d'
down_revision: Union[str, Sequence[str], None] = '99ccd5edb10d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_device_id', sa.Integer(), nullable=False),
    sa.Column('target_device_id', sa.Integer(), nullable=False),
    sa.Column('connection_label', sa.String(length=100), nullable=True),
    sa.Column('connection_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_connection_unique', 'device_connections', ['source_device_id', 'target_device_id'], unique=False)
    op.create_index(op.f('ix_device_connections_id'), 'device_connections', ['id'], unique=False)
    op.create_index(op.f('ix_device_connections_source_device_id'), 'device_connections', ['source_device_id'], unique=False)
    op.create_index(op.f('ix_device_connections_target_device_id'), 'device_connections', ['target_device_id'], unique=False)
    op.create_table('device_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('check_method', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('snmp_data', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_device_checked', 'device_status', ['device_id', 'checked_at'], unique=False)
    op.create_index(op.f('ix_device_status_checked_at'), 'device_status', ['checked_at'], unique=False)
    op.create_index(op.f('ix_device_status_device_id'), 'device_status', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_status_id'), 'device_status', ['id'], unique=False)
    op.create_table('device_status_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('last_status', sa.String(length=20), nullable=False),
    sa.Column('last_response_time_ms', sa.Float(), nullable=True),
    sa.Column('last_check_method', sa.String(length=20), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_online', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_online', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_offline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.create_index(op.f('ix_device_status_summary_id'), 'device_status_summary', ['id'], unique=False)
    op.create_index(op.f('ix_device_status_summary_last_status'), 'device_status_summary', ['last_status'], unique=False)
    op.add_column('devices', sa.Column('node_id', sa.String(length=50), nullable=False))
    op.add_column('devices', sa.Column('nombre_dispositivo', sa.String(length=100), nullable=False))
    op.add_column('devices', sa.Column('tipo', sa.String(length=50), nullable=False))
    op.add_column('devices', sa.Column('ip', sa.String(length=50), nullable=False))
    op.add_column('devices', sa.Column('mac', sa.String(length=50), nullable=True))
    op.add_column('devices', sa.Column('gateway', sa.String(length=50), nullable=True))
    op.add_column('devices', sa.Column('vlan', sa.String(length=20), nullable=True))
    op.add_column('devices', sa.Column('puerto', sa.String(length=50), nullable=True))
    op.add_column('devices', sa.Column('ubicacion', sa.String(length=255), nullable=True))
    op.add_column('devices', sa.Column('descripcion', sa.Text(), nullable=True))
    op.add_column('devices', sa.Column('position_x', sa.Float(), nullable=True))
    op.add_column('devices', sa.Column('position_y', sa.Float(), nullable=True))
    op.drop_index(op.f('ix_devices_DeviceName'), table_name='devices')
    op.create_index(op.f('ix_devices_ip'), 'devices', ['ip'], unique=True)
    op.create_index(op.f('ix_devices_node_id'), 'devices', ['node_id'], unique=True)
    op.drop_column('devices', 'DeviceDescription')
    op.drop_column('devices', 'Status')
    op.drop_column('devices', 'ImagenDispositivo')
    op.drop_column('devices', 'DeviceName')
    op.drop_column('devices', 'DeviceIP')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('DeviceIP', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('devices', sa.Column('DeviceName', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('devices', sa.Column('ImagenDispositivo', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('Status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('DeviceDescription', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_devices_node_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_ip'), table_name='devices')
    op.create_index(op.f('ix_devices_DeviceName'), 'devices', ['DeviceName'], unique=True)
    op.drop_column('devices', 'position_y')
    op.drop_column('devices', 'position_x')
    op.drop_column('devices', 'descripcion')
    op.drop_column('devices', 'ubicacion')
    op.drop_column('devices', 'puerto')
    op.drop_column('devices', 'vlan')
    op.drop_column('devices', 'gateway')
    op.drop_column('devices', 'mac')
    op.drop_column('devices', 'ip')
    op.drop_column('devices', 'tipo')
    op.drop_column('devices', 'nombre_dispositivo')
    op.drop_column('devices', 'node_id')
    op.drop_index(op.f('ix_device_status_summary_last_status'), table_name='device_status_summary')
    op.drop_index(op.f('ix_device_status_summary_id'), table_name='device_status_summary')
    op.drop_table('device_status_summary')
    op.drop_index(op.f('ix_device_status_id'), table_name='device_status')
    op.drop_index(op.f('ix_device_status_device_id'), table_name='device_status')
    op.drop_index(op.f('ix_device_status_checked_at'), table_name='device_status')
    op.drop_index('idx_device_checked', table_name='device_status')
    op.drop_table('device_status')
    op.drop_index(op.f('ix_device_connections_target_device_id'), table_name='device_connections')
    op.drop_index(op.f('ix_device_connections_source_device_id'), table_name='device_connections')
    op.drop_index(op.f('ix_device_connections_id'), table_name='device_connections')
    op.drop_index('idx_connection_unique', table_name='device_connections')
    op.drop_table('device_connections')
    # ### end Alembic commands ###
